version: "3.9"

services:

  # proxy:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   image: webtice-server
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - butcherdb

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   environment:
  #     FRONTEND_DEBUG_MODE: ${FRONTEND_DEBUG_MODE}
  #     FRONTEND_PRODUCTION_URL: ${FRONTEND_PRODUCTION_URL}
  #   depends_on:
  #     - backend

  butcherdb:
    image: postgres:12
    volumes:
      - butcher-app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  butcher-app-db-data:
